#!/bin/bash
cd /home/mahesh/mahesh/edinburgh/repos/parsec-3.0

source env.sh

mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/mahesh/mahesh/edinburgh/repos/primesim/bin/prime /home/mahesh/mahesh/edinburgh/repos/primesim/xml/config.xml /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out : -np 1 parsecmgmt -a run -p blackscholes -i simlarge -n 2 -c gcc-pthreads -s "pin.sh -ifeellucky -t /home/mahesh/mahesh/edinburgh/repos/primesim/bin/prime.so -c /home/mahesh/mahesh/edinburgh/repos/primesim/xml/config.xml -o /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out --"

cat /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out_1 /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out_0 > /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out

rm -f /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out_0
rm -f /home/mahesh/mahesh/edinburgh/repos/primesim/output/config.out_1


 618  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1
  619  make
  620  config_prime 
  621  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1
  622  make
  623  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1
  624  make
  625  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1
  626  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 3
  627  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1

  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config.xml /home/s1797403/repos/primesim/output/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config.xml -o /home/s1797403/repos/primesim/output/config.out -- /home/s1797403/repos/primesim/pbench/atomics/atomics 1

#Mahesh

#Atomic Pin

 556  pin.sh -ifeellucky -t /home/s1797403/repos/primesim/ppin/acqrel/bin/acqrel.so -- ../../../pbench/atomics/atomics 1 
  557  pin.sh -ifeellucky -t /home/s1797403/repos/primesim/ppin/acqrel/bin/acqrel.so -- ../../../pbench/atomics/atomics 1 
  558  pin.sh -ifeellucky -t /home/s1797403/repos/primesim/ppin/acqrel/bin/acqrel.so -- ../../../pbench/atomics/atomics 1 >> tmp.txt
  559  gedit tmp.txt 
  560  pin.sh -ifeellucky -t /home/s1797403/repos/primesim/ppin/acqrel/bin/acqrel.so -- ../../../pbench/atomics/atomics 1 > tmp.txt

pin.sh -ifeellucky -t /home/s1797403/repos/primesim/ppin/acqrel/bin/acqrel.so -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 2 -i 100 -r 200 -d 10 -x 6 -u 50 


2019/04/09#################################################################################################################################
 mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  507  source ../runprime/env.sh 
  508  make
  509  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  510  make
  511  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  512  make
  513  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  514  make
  515  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  516  make
  517  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  518  make
  519  make
  520  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 5 -r 10 -d 10 -x 6 -u 50
  521  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  522  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  523  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  524  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  525  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  526  make
  527  make -B
  528  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  529  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  530  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  531  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  532  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  533  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  534  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  535  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  536  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  537  pwd
  538  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50

  545  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  546  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  547  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  548  git status
  549  git commit -m "bep complete and run syncbench" src/system.cpp 
  550  git status
  551  git push origin dimp
  552  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  553  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  554  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 10000 -d 10 -x 6 -u 100
  555  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  556  make
  557  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  558  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  559  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  560  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 500 -r 1000 -d 10 -x 6 -u 50
  561  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_0.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_0.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  562  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  563  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 31 -i 100 -r 200 -d 10 -x 6 -u 50
  564  make -B
  565  make
  566  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 2 -i 100 -r 200 -d 10 -x 6 -u 50
  567  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/bstree -t 2 -i 100 -r 200 -d 10 -x 6 -u 50


2019/04/10##########################################################################################################
Error command "Segmentation Fault"---------
mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50


mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50
  688  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50
  689  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 200 -u 50
  690  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50
  691  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 10000 -u 50
  692  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 100 -r 10000 -u 50
  693  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 31 -i 1000 -r 10000 -u 50
  694  ls
  695  history > scripts/history_61_error.log
  696  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50
  697  uname -a
  698  lscpu
  699  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_3.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_3.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/hashmap -t 61 -i 100 -r 200 -u 50

 
 Error skiplist-rotating 
 prime: src/cache.cpp:562: int Cache::addSyncLine(InsMem*): Assertion `syncmap.size < 1000 failed.
[albert]s1797403: mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 /home/s1797403/repos/primesim/bin/prime /home/s1797403/repos/primesim/xml/config_4.xml /home/s1797403/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t /home/s1797403/repos/primesim/bin/prime.so -c /home/s1797403/repos/primesim/xml/config_4.xml -o /home/s1797403/repos/primesim/output/syncbench-fixed/config.out -- /home/s1797403/repos/primesim/pbench/syncbench/bin/skiplist-rotating-c -t 31 -i 100 -r 500 -u 50 -x 6




2019/04/12
 mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -o 1000 -u 50 -x 6
  516  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -o 1000 -u 50 -x 6
  517  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 100 -r 200 -o 1000 -u 50 -x 6
  518  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 500 -o 1000 -u 50 -x 6
  519  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 500 -o 1000 -u 50 -x 6
  520  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 50 -x 6 && mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 50 -x 6
  521  pwd
  522* mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 50 -x 6 && mpiexec --verbose --display-map --display-al100cation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 100 -x 6


  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 50 -x 6 && mpiexec --verbose --display-map --display-al100cation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 100 -x 6
mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 20 -x 6 && mpiexec --verbose --display-map --display-al100cation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 20 -x 6

mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 5000 -o 10000 -u 20 -x 6 && mpiexec --verbose --display-map --display-al100cation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 5000 -o 10000 -u 20 -x 6

#checking update rate and 
mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 20 -x 6 && mpiexec --verbose --display-map --display-al100cation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 20 -x 6

mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 80 -x 6 \
&& \
mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 31 -i 500 -r 1000 -o 1000 -u 80 -x 6


mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 16 -i 500 -r 1000 -o 1000 -u 50 -x 6









2019/05/12 Nes Runiing. FOund the bug in BSTREE and observe there are no insets at display-allocation
  541  make
  542  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 16 -i 500 -r 1000 -o 1000 -u 50 -x 6
  543  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 16 -i 500 -r 1000 -o 1000 -u 100 -x 6
  544  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  545  pwd
  546  source env.sh 
  547  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  548  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_1.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_1.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  549  make
  550  git status
  551  git pull origin dimp
  552  make -B
  553  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  554  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  555  pwd
  556  make -
  557  make -B
  558  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  559  make -B
  560  make -B
  561  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 2 -i 100 -r 200 -o 100 -u 100 -x 6
  562  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/lfqueue -t 8 -i 1000 -r 4000 -o 1000 -u 100 -x 6
  563  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 8 -i 1000 -r 4000 -o 1000 -u 100 -x 6
  564  gedit output/syncbench-fixed/config.out_1 
  565  gedit output/syncbench-fixed/config.out_0 
  566  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 8 -i 1 -r 4000 -o 1000 -u 100 -x 6
  567  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 8 -i 1 -r 64000 -o 1000 -u 100 -x 6
  568  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 8 -i 1 -r 64000 -o 1000 -u 100 -x 6
  569  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 8 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  570  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/skiplist-rotating-c -t 8 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  571  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 8 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  572  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 16 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  573  gedit output/syncbench-fixed/config.out0
  574  gedit output/syncbench-fixed/config.out_0 
  575  pwd
  576  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 16 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  577  ls
  578  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 1000 -r 64000 -o 1000 -u 70 -x 6
  579  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 1000 -r 64000 -o 1000 -u 70 -x 6
  580  ./${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 1000 -r 64000 -o 1000 -u 70 -x 6
  581  cd pbench/syncbench/bin/
  582  ./bstree -t 4 -i 1000 -r 64000 -o 1000 -u 70 -x 6
  583  ./bstree -t 4 -i 500 -r 64000 -o 1000 -u 70 -x 6
  584  ./bstree -t 4 -i 999 -r 64000 -o 1000 -u 70 -x 6
  585  ./bstree -t 4 -i 700 -r 64000 -o 1000 -u 70 -x 6
  586  ./skiplist-rotating-c -t 4 -i 700 -r 64000 -o 1000 -u 70 -x 6
  587  ./bstree -t 4 -i 700 -r 64000 -o 1000 -u 70 -x 6
  588  ./bstree -t 4 -i 700 -r 64000 -o 1000 -u 70 -x 6
  589  ./bstree -t 4 -i 700 -r 64000 -o 1000 -u 100 -x 6
  590  ./bstree -t 4 -i 1 -r 64000 -o 1000 -u 100 -x 6
  591  ./hashmap  -t 4 -i 1 -r 64000 -o 1000 -u 100 -x 6
  592  ./hashmap  -t 4 -i 500 -r 64000 -o 1000 -u 100 -x 6
  593  ./hashmap  -t 4 -i 1000 -r 64000 -o 1000 -u 100 -x 6
  594  ./hashmap  -t 4 -i 4000 -r 64000 -o 1000 -u 100 -x 6
  595  ./hashmap  -t 4 -i 10000 -r 64000 -o 1000 -u 100 -x 6
  596  ./hashmap  -t 4 -i 500 -r 2000 -o 1000 -u 100 -x 6
  597  ./hashmap  -t 4 -i 500 -r 2000 -o 2000 -u 100 -x 6
  598  ./hashmap  -t 4 -i 500 -r 8000 -o 2000 -u 100 -x 6
  599  ./hashmap  -t 4 -i 1000 -r 8000 -o 2000 -u 100 -x 6
  600  ./hashmap  -t 4 -i 1000 -r 6000 -o 2000 -u 100 -x 6
  601  ./hashmap  -t 4 -i 1000 -r 64000 -o 2000 -u 100 -x 6
  602  ./linkedlist  -t 4 -i 1000 -r 64000 -o 2000 -u 100 -x 6
  603  cd ..
  604  cd ..
  605  pwd
  606  cd ..
  607  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 64000 -o 1000 -u 70 -x 6
  608  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 64000 -o 1000 -u 70 -x 6
  609  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 4000 -o 1000 -u 70 -x 6
  610  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 1000 -o 1000 -u 100 -x 6
  611  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 100 -o 1000 -u 100 -x 6
  612  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 100 -o 1000 -u 100 -x 6
  613  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  614  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  615  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/bstree -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  616  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_4.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_4.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  617  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/linkedlist -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  618  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/hashmap -t 4 -i 0 -r 10 -o 1000 -u 100 -x 6
  619  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/hashmap -t 4 -i 0 -r 10 -o 1000 -u 100
  620  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/skiplist-rotating-c -t 4 -i 0 -r 10 -o 1000 -u 100


  mpiexec --verbose --display-map --display-allocation -mca btl_sm_use_knem 0 -np 1 ${HOME}/repos/primesim/bin/prime ${HOME}/repos/primesim/xml/config_3.xml ${HOME}/repos/primesim/output/syncbench-fixed/config.out : -np 1 pin.sh -ifeellucky -t ${HOME}/repos/primesim/bin/prime.so -c ${HOME}/repos/primesim/xml/config_3.xml -o ${HOME}/repos/primesim/output/syncbench-fixed/config.out -- ${HOME}/repos/primesim/pbench/syncbench/bin/skiplist-rotating-c -t 4 -i 0 -r 10 -o 1000 -u 100

#Still only single thread is running

Set type     : BST
Duration     : 10
Initial size : 1000
Nb threads   : 16
Value range  : 64000
Seed         : 0
Update rate  : 100
Lock alg.    : 6
Alternate    : 0
Effective    : 1
Operations    : 1000
Type sizes   : int=4/long=8/ptr=8/word=8
Adding 1000 entries to set
Set size (TENTATIVE) : 1000
Level max    : 0
Creating thread 0
Creating thread 1
[PriME] Thread 1 begins at cycle 6453114
